#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApplication.Resource", IsApplication=true)]

namespace TestApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f01001a
			public const int confirm_logout = 2130771994;
			
			// aapt resource value: 0x7f010014
			public const int done_button_background = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int done_button_text = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int extra_fields = 2130771983;
			
			// aapt resource value: 0x7f01001b
			public const int fetch_user_info = 2130771995;
			
			// aapt resource value: 0x7f01001f
			public const int is_cropped = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int login_text = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int logout_text = 2130771997;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010015
			public const int multi_select = 2130771989;
			
			// aapt resource value: 0x7f01001e
			public const int preset_size = 2130771998;
			
			// aapt resource value: 0x7f010016
			public const int radius_in_meters = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int results_limit = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int search_text = 2130771992;
			
			// aapt resource value: 0x7f01000e
			public const int show_pictures = 2130771982;
			
			// aapt resource value: 0x7f010019
			public const int show_search_box = 2130771993;
			
			// aapt resource value: 0x7f010010
			public const int show_title_bar = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int title_bar_background = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int title_text = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_blue = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_loginview_text_color = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_usersettingsfragment_connected_text_color = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int common_signin_btn_text_dark = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_signin_btn_text_light = 2130968592;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_loginview_height = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_loginview_padding_bottom = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_loginview_padding_left = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_loginview_padding_right = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_padding_top = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_loginview_text_size = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_loginview_width = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_profilepictureview_preset_size_large = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_profilepictureview_preset_size_small = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_check = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_check_off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_check_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_grey_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_grey_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_grey_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_close = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_list_divider = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_list_section_header_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_loginbutton_blue = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_loginbutton_blue_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_loginbutton_blue_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_loginbutton_blue_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_loginbutton_silver = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_picker_item_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_picker_list_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_picker_list_longpressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_picker_list_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_picker_list_selector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_picker_list_selector_background_transition = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_picker_list_selector_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_picker_top_button = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_place_default_icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_profile_default_icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_profile_picture_blank_portrait = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_profile_picture_blank_square = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_top_background = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_top_button = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_icon_disabled_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_icon_disabled_focus_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_icon_disabled_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_icon_focus_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_icon_focus_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_icon_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_icon_normal_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_icon_normal_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_icon_pressed_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_icon_pressed_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_signin_btn_text_disabled_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_signin_btn_text_disabled_focus_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_signin_btn_text_disabled_focus_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_signin_btn_text_disabled_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_signin_btn_text_focus_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_signin_btn_text_focus_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_signin_btn_text_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_signin_btn_text_normal_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_signin_btn_text_normal_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_signin_btn_text_pressed_dark = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_signin_btn_text_pressed_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Icon = 2130837559;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int MMAdLayout = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int adView = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_login_activity_progress_bar = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_picker_activity_circle = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_picker_checkbox = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_picker_checkbox_stub = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int com_facebook_picker_divider = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int com_facebook_picker_done_button = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_picker_image = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int com_facebook_picker_list_section_header = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_picker_list_view = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_picker_profile_pic_stub = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_picker_row_activity_circle = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_picker_title = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int com_facebook_picker_title_bar = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int com_facebook_picker_title_bar_stub = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int com_facebook_picker_top_bar = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int com_facebook_placepickerfragment_search_box_stub = 2131034134;
			
			// aapt resource value: 0x7f05001b
			public const int com_facebook_usersettingsfragment_login_button = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int com_facebook_usersettingsfragment_logo_image = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int com_facebook_usersettingsfragment_profile_name = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int large = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int picker_subtitle = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int search_box = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int small = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_friendpickerfragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_activity_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_picker_activity_circle_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_checkbox = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_image = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_list_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_section_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_search_box = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_title_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar_stub = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_placepickerfragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment_list_row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_usersettingsfragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Main = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06002f
			public const int ApplicationName = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int Hello = 2131099694;
			
			// aapt resource value: 0x7f060010
			public const int auth_client_needs_enabling_title = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int auth_client_needs_installation_title = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int auth_client_needs_update_title = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int auth_client_play_services_err_notification_msg = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_requested_by_msg = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int auth_client_using_bad_version_title = 2131099663;
			
			// aapt resource value: 0x7f060024
			public const int com_facebook_choose_friends = 2131099684;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_dialogloginactivity_ok_button = 2131099669;
			
			// aapt resource value: 0x7f060028
			public const int com_facebook_internet_permission_error_message = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int com_facebook_internet_permission_error_title = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int com_facebook_loading = 2131099686;
			
			// aapt resource value: 0x7f06001b
			public const int com_facebook_loginview_cancel_action = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_loginview_log_in_button = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int com_facebook_loginview_log_out_action = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_loginview_log_out_button = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_loginview_logged_in_as = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int com_facebook_loginview_logged_in_using_facebook = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int com_facebook_logo_content_description = 2131099676;
			
			// aapt resource value: 0x7f060025
			public const int com_facebook_nearby = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int com_facebook_picker_done_button_text = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int com_facebook_placepicker_subtitle_format = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131099682;
			
			// aapt resource value: 0x7f06002b
			public const int com_facebook_requesterror_password_changed = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int com_facebook_requesterror_permissions = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int com_facebook_requesterror_reconnect = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int com_facebook_requesterror_relogin = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int com_facebook_requesterror_web_login = 2131099689;
			
			// aapt resource value: 0x7f06001d
			public const int com_facebook_usersettingsfragment_log_in_button = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int com_facebook_usersettingsfragment_logged_in = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131099679;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_unknown_issue = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_unsupported_text = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_unsupported_title = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_button = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int common_signin_button_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text_long = 2131099662;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_loginview_default_style = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_loginview_silver_style = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771989};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771998,
					2130771999};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
